### PR TITLE
Milestone 5

### PR DESCRIPTION
**Pull request by IBUNHABIBU**
Coding the friendship for the 5th milestone

### CODE REVIEW

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

### Hello team  🌟

**Great work on this project, however, the following changes need to be done before moving on ⬇️** 

* [ ] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)).

* [ ] There is a button to send a friendship request to another user on their profile page (single user's view page) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)).

* [ ] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)), I was able to see all the posts even of the users that I'm not friends with.

- This Capybara test is failing:

> Following friend  List of all users with friendship status

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Comment by IBUNHABIBU** [comment]
> Coding the friendship for the 5th milestone

we fixed the lint errors
we fixed the rspec error to pass
we added the link to add and accept friendship in the user profile

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

### Hello team  🌟

**Great work implementing the changes but, the following changes need to be done before moving on ⬇️** 

* [ ] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)), I was able to see posts of the users that I'm not friend with.

* [ ] The linter check is red, please fix all the linting errors in the pull request.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Comment by IBUNHABIBU** [comment]
-We have fixed the timeline
-We have fixed the rubocop errors

**Review by wathigo — APPROVED** [review]
Approved :heavy_check_mark: 
Great work implementing timeline posts.

**You may move on.**

Happy Coding :computer: 
Simon Wathigo

**Pull request merged**
